### ISSUE TITLE
AugmentationStrategy implementation is missing

### ISSUE THREAD

**Issue by valeriylo** [wanggynpuer/3D-RCNet#2]
Hey, I struggle to find where's the implementation for

```
from augmentationStrategy import augment
from augmentationStrategy import augmentTest
```
or what package are you using for that

**Comment by wanggynpuer** [comment]
> Hey, I struggle to find where's the implementation for
> 
> ```
> from augmentationStrategy import augment
> from augmentationStrategy import augmentTest
> ```
> 
> or what package are you using for that

I sincerely apologize for any inconvenience caused. The **augmentationStrategy.py** has been added, and I truly appreciate your valuable feedback. Please don't hesitate to reach out if you have any further questions or concerns.

**Comment by valeriylo** [comment]
@wanggynpuer could you also provide `data_preprocess/data_list/Indian_pines_train.txt`, `.../Indian_pines_test.txt` and `Indian_pines.txt` params files.

I created my own from the provided default args values, but unfortunately there's parsing issue in `functions_for_training.py` on line `sample_path = self.list_txt[index].split(' ')`

Here's `Indian_pines_train.txt` I created

```
dataset=Indian_pines
model_name=HSIVit
use_cuda=True
restore=False
batch_size=64
test_batch_size=64
epochs=300
lr=0.0005
momentum=0.9
seed=0
model_save_interval=300
sheet_id=2
beta=1.0
cutmix_prob=1.0
num_workers=10
pin_mem=True
```

and error code

```
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/wd/3d-rcnet/training/functions_for_training.py", line 38, in __getitem__
    label = sample_path[1][:-1]
IndexError: list index out of range
```

**Comment by wanggynpuer** [comment]
> @wanggynpuer could you also provide `data_preprocess/data_list/Indian_pines_train.txt`, `.../Indian_pines_test.txt` and `Indian_pines.txt` params files.
> 
> I created my own from the provided default args values, but unfortunately there's parsing issue in `functions_for_training.py` on line `sample_path = self.list_txt[index].split(' ')`
> 
> Here's `Indian_pines_train.txt` I created
> 
> ```
> dataset=Indian_pines
> model_name=HSIVit
> use_cuda=True
> restore=False
> batch_size=64
> test_batch_size=64
> epochs=300
> lr=0.0005
> momentum=0.9
> seed=0
> model_save_interval=300
> sheet_id=2
> beta=1.0
> cutmix_prob=1.0
> num_workers=10
> pin_mem=True
> ```
> 
> and error code
> 
> ```
> Original Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
>     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/wd/3d-rcnet/training/functions_for_training.py", line 38, in __getitem__
>     label = sample_path[1][:-1]
> IndexError: list index out of range
> ```
I have now updated the repository, adding the paper reference as well as the **Indian_pines_split.txt file** to the **data_list** directory. I hope this helps!
